package tech.ydb.mv.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeSet;

import tech.ydb.mv.MvConfig;
import tech.ydb.mv.YdbConnector;
import tech.ydb.mv.parser.MvDescriber;
import tech.ydb.mv.parser.MvValidateBasic;
import tech.ydb.mv.parser.MvValidateSql;

/**
 * Aggregated metadata cache used by the YDB Materializer.
 *
 * It includes the definitions of the materialized views, handlers, and on input
 * and output tables' structure. Input and output tables are handled separately
 * because they can belong to different databases, and, in theory, may have
 * overlappling names (e.g. the same table name may be used for two different
 * tables, one being used as input, and another as the destination for the MV).
 *
 * Metadata cache also includes the list of warnings and errors generated by
 * parsing and validation of MV and handlers definitions.
 *
 * @author zinal
 */
public class MvMetadata {

    private String dictionaryConsumer = MvConfig.HANDLER_DICTIONARY;

    private final HashMap<String, MvView> views = new HashMap<>();
    private final HashMap<String, MvHandler> handlers = new HashMap<>();
    private final HashMap<String, MvTableInfo> inputTables = new HashMap<>();
    private final HashMap<String, MvTableInfo> outputTables = new HashMap<>();

    private final ArrayList<MvIssue> errors = new ArrayList<>();
    private final ArrayList<MvIssue> warnings = new ArrayList<>();

    public MvMetadata() {
    }

    public String getDictionaryConsumer() {
        return dictionaryConsumer;
    }

    public void setDictionaryConsumer(String dictionaryConsumer) {
        this.dictionaryConsumer = dictionaryConsumer;
    }

    public Map<String, MvView> getViews() {
        return views;
    }

    public Map<String, MvHandler> getHandlers() {
        return handlers;
    }

    public Map<String, MvTableInfo> getInputTables() {
        return inputTables;
    }

    public Map<String, MvTableInfo> getOutputTables() {
        return outputTables;
    }

    public ArrayList<MvIssue> getErrors() {
        return errors;
    }

    public ArrayList<MvIssue> getWarnings() {
        return warnings;
    }

    public boolean isValid() {
        return errors.isEmpty();
    }

    public MvView addView(MvView v) {
        return views.put(v.getName(), v);
    }

    public MvHandler addHandler(MvHandler h) {
        return handlers.put(h.getName(), h);
    }

    public void addIssue(MvIssue i) {
        if (i.isError()) {
            errors.add(i);
        } else {
            warnings.add(i);
        }
    }

    public void addIssues(Collection<? extends MvIssue> ix) {
        for (MvIssue i : ix) {
            addIssue(i);
        }
    }

    /**
     * Perform metadata validation.
     *
     * @param input YDB connection to test SQL fragments against.
     * @return true, if no errors detected, false otherwise
     */
    public boolean validate(YdbConnector input) {
        if (!isValid()) {
            return false;
        }
        boolean valid = new MvValidateBasic(this).validate();
        if (valid && input != null) {
            valid = new MvValidateSql(this, input).validate();
        }
        return valid;
    }

    /**
     * Load the missing parts of metadata and perform validation.
     *
     * Table, column and changefeed information is loaded using the helper
     * object passed.
     *
     * @param inputMeta Helper for metadata retrieval for the source database
     * @param outputMeta Helper for metadata retrieval for the destination
     * database
     * @return true, if no errors detected, false otherwise
     */
    public boolean linkAndValidate(MvDescriber inputMeta, MvDescriber outputMeta) {
        if (!isValid()) {
            return false;
        }
        inputTables.clear();
        outputTables.clear();
        for (String tabname : collectInputTables()) {
            MvTableInfo ti = inputMeta.describeTable(tabname);
            if (ti != null) {
                inputTables.put(tabname, ti);
            }
        }
        for (String tabname : collectOutputTables()) {
            MvTableInfo ti = outputMeta.describeTable(tabname);
            if (ti != null) {
                outputTables.put(tabname, ti);
            }
        }
        linkTables();
        linkColumns();
        if (!validate(inputMeta.getYdb())) {
            return false;
        }
        views.values().forEach(target -> target.updateUsedColumns());
        return true;
    }

    private TreeSet<String> collectInputTables() {
        TreeSet<String> ret = new TreeSet<>();
        for (MvView v : views.values()) {
            for (var t : v.getParts().values()) {
                // source tables
                for (var r : t.getSources()) {
                    ret.add(r.getTableName());
                }
            }
        }
        // possible extra inputs (which may be missing in the views)
        for (MvHandler h : handlers.values()) {
            for (MvInput i : h.getInputs().values()) {
                ret.add(i.getTableName());
            }
        }
        return ret;
    }

    private TreeSet<String> collectOutputTables() {
        TreeSet<String> ret = new TreeSet<>();
        for (MvView v : views.values()) {
            // target table for each mv
            ret.add(v.getName());
        }
        return ret;
    }

    private void linkTables() {
        for (var v : views.values()) {
            v.setTableInfo(outputTables.get(v.getName()));
            for (var t : v.getParts().values()) {
                for (var js : t.getSources()) {
                    js.setTableInfo(inputTables.get(js.getTableName()));
                }
            }
        }
        for (MvHandler h : handlers.values()) {
            for (MvInput i : h.getInputs().values()) {
                i.setTableInfo(inputTables.get(i.getTableName()));
            }
        }
    }

    private void linkColumns() {
        for (var v : views.values()) {
            MvTableInfo ti = v.getTableInfo();
            if (ti == null) {
                continue;
            }
            for (var t : v.getParts().values()) {
                for (var column : t.getColumns()) {
                    column.setType(ti.getColumns().get(column.getName()));
                    v.addColumnIf(column);
                }
            }
        }
    }

    /**
     * Create a new MvMetadata instance as a subset of the current one.
     *
     * @param handler The handler which should be available in the subset
     * @return MvMetadata instance limited to the specified handler only
     */
    public MvMetadata subset(MvHandler handler) {
        if (!isValid()) {
            throw new IllegalStateException("Cannot subset a non-valid metadata");
        }
        if (handler != handlers.get(handler.getName())) {
            throw new IllegalArgumentException("Input handler is not included in the working set");
        }
        MvMetadata output = new MvMetadata();
        output.setDictionaryConsumer(dictionaryConsumer);
        output.addHandler(handler);
        for (MvView v : handler.getViews().values()) {
            output.addView(v);
        }
        return output;
    }

}
